### PR TITLE
"B.A.T." is not a valid windows directory name, can't end with dot

### PR DESCRIPTION
**Pull request by egzumer**
There is "B.A.T." and "B.A.T" directories in this repo. Windows automatically converts "B.A.T." to "B.A.T" upon creation which leads to clash error with the second "B.A.T" dir. Actually both directories contain the same data and one should be deleted.

### CODE REVIEW

**Review by bengtmartensson — APPROVED** [review]
There is obviously a duplicate in the data base, as pointed out in this PR. It is desirable to resolve this, so I approve of the change. However, not for the reason given -- it has as such nothing to do with Windows and its shortcomings.

**Comment by egzumer** [comment]
It's approved, but I'm still curious. Did you try to clone this repo on windows? Because it results in error, which has to be resolved manually. I wasn't aware that on windows you can't create directory ending with dot. Try it yourself.
Even better, try running in command line : "mkdir a..\\\"
:)

**Comment by probonopd** [comment]
Should we rename it to BAT for better compatibility? I have no Windows to test with.

**Comment by egzumer** [comment]
If you ask me only the last dot causes a headache. And to prove that it is a problem:
https://www.google.com/search?q=windows+dot+ended&oq=windows+dot+ended+&aqs=chrome..69i57j69i60.4680j0j7&sourceid=chrome&ie=UTF-8

**Pull request closed without merging**
