### PR TITLE
Normalizes most of the function names.

### PR DESCRIPTION
**Pull request by kdschlosser**
I wrote a script that parsed all of the files and normalized the function names. there are some that are "special" and will need to be manually looked over.

I would recommend creating some kind of a list of function names the user can pick from. I know there will be special use cases and there should also be a means to input the custom function name. When a custom name is entered the code should be flagged for review. This way you have some consistency. You will also be able to provide the user with a fantastic search. they can select the manufacturer of the remote and then select the function name they want from the list. This will retrieve all codes associated with the matching function name. then the user can decide which ones they want to use.

I know using the device id's and sub id's is easier for you and I. but the reality of it is the user is not going to know what in the world those are.. for example if wanting to lookup the Volume+ for a Sony AVR they are most likely not going to know the device id can be any one of the following ids 0x030, 0x00D, 0x02D, 0x00C, 0x02C, 0x012, 0x018, 0x090, 0x0B0 so it is better to enumerate all of the functions that match the device type that is selected. you can also do an explicit model lookup if this information was stored somewhere. I did not stumble across this in the database files as of yet if it does exist.

But the trick is to control how users are naming the functions so they will be the same across the board. almost all brands of remotes share the same button and same button names.. the other thing I noticed is that on many occasions a remote will have buttons on it that are not associated to the device type of the actual device.. We will use Sony again.. There can be buttons for controlling a TV on an AVR remote, these buttons use the device ID that matches up with the TV's A user is going to name the button TV_SOME_FUNCTION_NAME.. The function name should give the user a clue that the code that is used is not an AVR code but it is a TV code. This would need to be done in the function name. I have not come up with a nomenclature for this I am sure you could come up with something.

I am doing this house cleaning to get everything primed to build a mysql database with the information.

If you have a list of device id's to friendly names I would love to be able to also add this to the database.
The manufacturer names are already there. and if there are no model numbers I am going to set the database up so that model numbers can be used if wanted..

### CODE REVIEW

**Comment by probonopd** [comment]
Hi @kdschlosser, thanks for this PR.

Regarding consistent function/button names:

Yes, I agree this is a great thing to have. But how do we want to name the buttons? `lirc` has a predefined set of button names. Would it make sense to standardize on those, at least where possible?

https://gist.github.com/unforgiven512/0c232f4112b63021a8e0df6eedfb2ff3

Regarding device/model names:

In order to keep workload manageable and to make the database more "timeless" I have decided early on to not deal with individual device names but only with codesets. Usually the same codeset covers many similar devices from the same manufacturer. If you have sufficient data to build and maintain a halfway comprehensive list of models/devices then we should discuss including it. I don't have one.

**Comment by kdschlosser** [comment]
me personally do not care for the naming semantics having KEY_ or BTN_ before every function name does not need to be done.

I personally like to group buttons by category.
NUMBER.0,
NUMBER.1,
NUMBER.2

NAVIGATION.UP
NAVIGATION.DOWN
NAVIGATION.BACK

MEDIA.PLAY
MEDIA.PAUSE
MEDIA.STOP
The reason why is because of long press and shifting. where an ENTER button might also be the OK button but it uses a different code and falls into a different group

**Comment by kdschlosser** [comment]
This is something that you would have to like i guess I did it only because they were all over the place. if a simple drop down was provided with the most common function names i would think that people would try to follow the same kind of a naming convention if they wanted to add a button that was not in the list.

**Comment by Denneledoe** [comment]
@kdschlosser i hope it's not too much to ask, but do you still have the script you used to normalize the function names? I'm running into the same problem.

**Pull request closed without merging**
