### PR TITLE
Create NV-HV61

### PR DESCRIPTION
**Pull request by SS72post**
Panasonic NV-HC61 VCR recorder. Captured in Irscrutinizer

### CODE REVIEW

**Comment by probonopd** [comment]
Hi, `functionname` is missing for `panasonic	144	1	147`. Thanks!

**Review by SS72post — COMMENTED** [review]
B function labelled

**Comment by probonopd** [comment]
Thanks!

**Comment by bengtmartensson** [comment]
There is already a file for Panasonic 144,0

**Pull request closed without merging**
