### PR TITLE
Create 0,255.csv

### PR DESCRIPTION
**Pull request by nigelorr**
Generic 20x20 LED smart curtain, unable to find definitive manufacturer. 
Examples should be found  [here](https://www.aliexpress.com/w/wholesale-LED-smart-curtain.html)
NEC codes captured by [IR Remote ESP8266](https://github.com/crankyoldgit/IRremoteESP8266)

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @nigelorr. If you have any chance, are there any product numbers on the housing or the PCB?

**Comment by nigelorr** [comment]
The device itself is completely anonymous. However I found the original packaging which has Model BESL18 marked on it. Also FCC ID 2AKBP-BSL2 

However the device doesn't match the FCC photos, so may or may not be the same...

Hope that helps!

Nigel

**Comment by probonopd** [comment]
Thanks, this helps.

Do you think this is the device?
https://device.report/avatar/BESL18

**Comment by bengtmartensson** [comment]
I have heard somewhere that [Renesas](https://en.wikipedia.org/wiki/Renesas_Electronics) (which is the successor of the NEC firm), requires a license fee for commercial uses of the NEC protocol, with the exception of the case were D (the device number) is =0, and S (subdevice) is default (=255). For this reason, there are a lot of "cheap" devices using the NEC protocol with D=0 (like the present one). So it may not be very valuable... although it does not hurt either...

**Comment by probonopd** [comment]
Interesting. Patents typically last for 20 years from the filing date. Since the NEC protocol was introduced in the early 1980s, any patents specific to the protocol would have likely expired by now. So I'd be surprised if Renesas could still charge for its use today on the basis of patents, but I am not a lawyer. Maybe they are charging for the device to be officially registered in their database or something like that? But then, a quick search in their support forum did not show anything relevant. Possibly it's an urban legend, but still to the effect that "cheap" devices stick to D=0. Or maybe that's just the default in most libraries, and the device manufacturers say to themselves, why change it if it works.

**Comment by nigelorr** [comment]
Yes, that looks like it. Thanks

**Pull request merged**
