### PR TITLE
Create SLR Camera remote

### PR DESCRIPTION
**Pull request by SS72post**
Canon SLR Camera remote. Could ony capture as Girr raw file. Captured in Irscrutinizer

### CODE REVIEW

**Comment by probonopd** [comment]
Please use the CSV format we are using in the master branch of this repository, thanks!

**Review by SS72post — COMMENTED** [review]
If I export RAW signals to CSV i just get this. How do I export RAX to CSV

**Comment by SS72post** [comment]
Or do I export as Bracketed RAW

**Comment by bengtmartensson** [comment]
1. Raw signals with durations of 0 are meaningless. What does it mean, semantically, to send a gap of zero length? So the contribution cannot be accepted regardless of format. How have you gotten such measurements? (If you describe your setup, possibly I can help.)
2. irdb has only a very limited, "dumb" format, csv with three parameters.  Ii is not my decision, and have suggested an alternative, #58.
3. You are welcome to submit Girr files (parametrized as well as raw/pronto) to [GirrLib](https://github.com/bengtmartensson/GirrLib), as PR. But you need better meta data than "Canon SLR"; I have a Canon EOD450 with [these commands](https://github.com/bengtmartensson/GirrLib/blob/master/Girr/Canon/canon.girr).

**Comment by bengtmartensson** [comment]
Replaced by 0fc69be03e6b243c6df22bb53be2d70b8baaa71b

**Pull request closed without merging**
