### PR TITLE
update index and add a script for updating index

### PR DESCRIPTION
**Pull request by SIGUrger**
verify before merging

### CODE REVIEW

**Comment by SIGUrger** [comment]
a decreease in 200 lines seems odd probably incorrect but unsure what yet

**Comment by probonopd** [comment]
Thanks @SIGUrger. Not sure whether the index is even used by anyone or anything. Do you know?

**Comment by SIGUrger** [comment]
> Thanks @SIGUrger. Not sure whether the index is even used by anyone or anything. Do you know?

I was using it for a flipper zero project that's why I made the script. I haven't seen a **working** website use it anymore tho

**Comment by probonopd** [comment]
Well, since it doesn't remove any of the actual code files there is little danger in merging it; the indexes can't become more outdated than they already are...

**Pull request merged**
