### PR TITLE
fixed all CSV errors. 

### PR DESCRIPTION
**Pull request by Denneledoe**
removed unneeded commas, and all entries should be 5 frames wide.

had to do this by hand. it's not going to be perfect, but it should be compatible with something like Pandas now.

it seems there were too many commas generated, and some dataframes were 6, 7, or 8 frames wide, instead of 5.

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks, but to be honest I am not sure whether there was something broken. Some protocols have more parameters than others.

What is Pandas?

**Comment by Denneledoe** [comment]
Pandas is a data science library for Python 3. you can read CSV with it, but for CSV to be valid, it has to be consistent on entries.
it seems only 5 are ever needed: protocol, device, subdevice, an function.

there were too many commas generated, which made the CSV invalid, as it sees the commas as frame separators, when there are more commas than you need, which adds frames to the CSV, it shouldn't have

**Comment by Denneledoe** [comment]
in short, with these CSV errors fixed, you can now automatically load the entire codes directory in using pandas, and other data science libraries

**Comment by probonopd** [comment]
Thanks for the explanation @Denneledoe

**Review by bengtmartensson — APPROVED** [review]
This PR fixes a number of broken CSV files. I have not checked all, but the ones I checked was broken before, but not after the fix. I recommend merging.

**Comment by probonopd** [comment]
Thank you very much for having taken the time to fix everything by hand @Denneledoe and thanks for reviewing @bengtmartensson

**Comment by Denneledoe** [comment]
haha, thanks @probonopd 
i just kept running it, seeing where it stopped, removing the commas there, and repeating that for the entire afternoon ;)

first time contributing open source

**Comment by probonopd** [comment]
Congratulations to your first open source contribution. Keep it up!

**Pull request merged**
