### PR TITLE
Removed duplicates and added missing

### PR DESCRIPTION
**Pull request by dobbelina**
The removed duplicates are not toggle bits, they are identical, hence useless.

### CODE REVIEW

**Review by bengtmartensson — APPROVED** [review]
Without having checked every detail, this looks good to me.

**Comment by dobbelina** [comment]
Added missing PICTURE OFF on PICTURE OFF,Sony12,1,-1,62

**Comment by probonopd** [comment]
Please click "Ready for review" once you think this is ready for merge. Thank you @dobbelina

**Comment by dobbelina** [comment]
I think it's about ok now.
I have more Sony codes, but i can make another pull request later when i have the time to add them.

**Comment by probonopd** [comment]
Thank you very much @dobbelina

**Pull request merged**
